const term = [
    "Pain",
    "Baguette",
    "Croissant",
    "Brioche",
    "Pain de mie",
    "Biscottes",
    "Farine",
    "Sucre",
    "Sel",
    "Poivre",
    "Huile d'olive",
    "Huile de tournesol",
    "Vinaigre balsamique",
    "Vinaigre de vin",
    "Moutarde",
    "Mayonnaise",
    "Ketchup",
    "Sauce soja",
    "Sauce tomate",
    "Pâtes",
    "Riz",
    "Semoule",
    "Quinoa",
    "Lentilles",
    "Haricots blancs",
    "Haricots rouges",
    "Pois chiches",
    "Blé",
    "Flocons d'avoine",
    "Muesli",
    "Cornflakes",
    "Biscuits",
    "Gâteaux",
    "Chocolat",
    "Bonbons",
    "Confiseries",
    "Yaourts",
    "Fromage blanc",
    "Crème fraîche",
    "Lait",
    "Beurre",
    "Fromage",
    "Camembert",
    "Brie",
    "Roquefort",
    "Emmental",
    "Chèvre",
    "Mascarpone",
    "Ricotta",
    "Mozzarella",
    "Parmesan",
    "Gorgonzola",
    "Bleu d'Auvergne",
    "Jambon blanc",
    "Jambon cru",
    "Saucisson",
    "Chorizo",
    "Salami",
    "Bacon",
    "Poulet",
    "Dinde",
    "Canard",
    "Pintade",
    "Crevettes",
    "Saumon",
    "Thon",
    "Sardines",
    "Maquereau",
    "Cabillaud",
    "Colin",
    "Haddock",
    "Merlu",
    "Morue",
    "Filet de poisson",
    "Steak haché",
    "Escalope",
    "Côtelette",
    "Rôti",
    "Boeuf",
    "Veau",
    "Agneau",
    "Porc",
    "Charcuterie",
    "Saucisses",
    "Chipolatas",
    "Lardons",
    "Steak",
    "Poitrine de poulet",
    "Cuisses de poulet",
    "Ailes de poulet",
    "Pilons de poulet",
    "Cuisses de dinde",
    "Ailes de dinde",
    "Pilons de dinde",
    "Roti de dinde",
    "Rôti de porc",
    "Rôti de boeuf",
    "Rôti de veau",
    "Entrecôte",
    "Filet mignon",
    "Faux-filet",
    "Gigot",
    "Épaule d'agneau",
    "Poitrine de veau",
    "Langue de boeuf",
    "Foie de veau",
    "Foie de volaille",
    "Foie gras",
    "Magret de canard",
    "Cuisse de canard",
    "Couscous",
    "Paella",
    "Ratatouille",
    "Gratin dauphinois",
    "Purée de pommes de terre",
    "Frites",
    "Pommes de terre",
    "Légumes surgelés",
    "Fruits surgelés",
    "Pois surgelés",
    "Épinards surgelés",
    "Haricots verts surgelés",
    "Brocolis surgelés",
    "Carottes surgelées",
    "Petits pois surgelés",
    "Chou-fleur surgelé",
    "Courgettes surgelées",
    "Poivrons surgelés",
    "Tomates surgelées",
    "Pizzas surgelées",
    "Quiches surgelées",
    "Plats cuisinés surgelés",
    "Desserts glacés",
    "Glaces",
    "Sorbets",
    "Crèmes glacées",
    "Gaufres surgelées",
    "Crêpes surgelées",
    "Pâtes à pizza surgelées",
    "Nuggets de poulet",
    "Cordon bleu",
    "Poêlées surgelées",
    "Viandes surgelées",
    "Poissons surgelés",
    "Crevettes surgelées",
    "Fruits de mer surgelés",
    "Légumes en conserve",
    "Fruits en conserve",
    "Pois en conserve",
    "Haricots verts en conserve",
    "Maïs en conserve",
    "Champignons en conserve",
    "Tomates en conserve",
    "Olives en conserve",
    "Sardines en conserve",
    "Thon en conserve",
    "Maquereau en conserve",
    "Saumon en conserve",
    "Anchois en conserve",
    "Cœurs d'artichaut en conserve",
    "Poivrons en conserve",
    "Asperges en conserve",
    "Petits pois en conserve",
    "Jus de fruits",
    "Jus de légumes",
    "Jus de tomate",
    "Soda",
    "Eau gazeuse",
    "Eau plate",
    "Limonade",
    "Bière",
    "Vin rouge",
    "Vin blanc",
    "Vin rosé",
    "Champagne",
    "Apéritif",
    "Digestif",
    "Liqueur",
    "Whisky",
    "Rhum",
    "Vodka",
    "Gin",
    "Tequila",
    "Vermouth",
    "Cognac",
    "Armagnac",
    "Crème de cassis",
    "Crème de menthe",
    "Café",
    "Thé",
    "Infusions",
    "Céréales pour petit-déjeuner",
    "Barres de céréales",
    "Miel",
    "Confiture",
    "Nutella",
    "Beurre de cacahuète",
    "Moutarde à l'ancienne",
    "Moutarde au miel",
    "Moutarde forte",
    "Cornichons",
    "Olives",
    "Pâtes à tartiner",
    "Chips",
    "Popcorn",
    "Biscuits apéritif",
    "Sauces pour salade",
    "Vinaigrette",
    "Condiments",
    "Épices",
    "Herbes aromatiques",
    "Ail",
    "Oignon",
    "Échalote",
    "Gingembre",
    "Citron",
    "Orange",
    "Pomme",
    "Poire",
    "Banane",
    "Kiwi",
    "Ananas",
    "Mangue",
    "Melon",
    "Pastèque",
    "Cerise",
    "Fraises",
    "Framboises",
    "Myrtilles",
    "Mûres",
    "Abricots",
    "Pêches",
    "Prunes",
    "Raisins",
    "Pommes de terre",
    "Carottes",
    "Courgettes",
    "Aubergines",
    "Poivrons",
    "Tomates",
    "Concombres",
    "Salade verte",
    "Choux",
    "Brocolis",
    "Chou-fleur",
    "Radis",
    "Asperges",
    "Haricots verts",
    "Épinards",
    "Courges",
    "Laitue",
    "Persil",
    "Coriandre",
    "Basilic",
    "Menthe",
    "Romarin",
    "Thym",
    "Origan",
    "Ciboulette",
    "Estragon",
    "Laurier",
    "Cannelle",
    "Muscade",
    "Curry",
    "Paprika",
    "Piment",
    "Sel de mer",
    "Sel fin",
    "Poivre noir",
    "Poivre blanc",
    "Poivre de Cayenne",
    "Piment d'Espelette",
    "Sucre en poudre",
    "Sucre roux",
    "Sucre glace",
    "Farine de blé",
    "Farine de maïs",
    "Farine de seigle",
    "Farine de riz",
    "Levure chimique",
    "Levure de boulanger",
    "Huile de colza",
    "Huile de noix",
    "Huile de pépins de raisin",
    "Huile de coco",
    "Huile de palme",
    "Vinaigre de cidre",
    "Vinaigre de vin blanc",
    "Vinaigre blanc",
    "Vinaigre aromatisé",
    "Eau de toilette",
    "Dentifrice",
    "Brosse à dents",
    "Shampoing",
    "Après-shampoing",
    "Gel douche",
    "Savon",
    "Déodorant",
    "Rasoirs",
    "Mouchoirs en papier",
    "Papier toilette",
    "Cotons-tiges",
    "Serviettes hygiéniques",
    "Tampons",
    "Lingettes bébé",
    "Couches bébé",
    "Crème solaire",
    "Après-soleil",
    "Anti-moustiques",
    "Bougies",
    "Allumettes",
    "Batteries",
    "Ampoules",
    "Éponges",
    "Liquide vaisselle",
    "Produit vaisselle",
    "Tablettes lave-vaisselle",
    "Lessive liquide",
    "Lessive en poudre",
    "Assouplissant textile",
    "Détachant",
    "Désodorisant",
    "Nettoyant multi-usages",
    "Nettoyant vitres",
    "Nettoyant salle de bains",
    "Nettoyant cuisine",
    "Éponges abrasives",
    "Chiffons microfibres",
    "Sac poubelle",
    "Papier aluminium",
    "Film alimentaire",
    "Sacs de congélation",
    "Papier cuisson",
    "Gants de ménage",
    "Sérum physiologique",
    "Solution saline",
    "Compresses",
    "Pansements",
    "Bandes adhésives",
    "Antiseptique",
    "Thermomètre",
    "Mouche-bébé",
    "Trousse de premiers secours",
    "Ciseaux",
    "Pince à épiler",
    "Brosse à cheveux",
    "Peigne",
    "Sèche-cheveux",
    "Fer à lisser",
    "Fer à friser",
    "Tondeuse à cheveux",
    "Brosses à ongles",
    "Lime à ongles",
    "Vernis à ongles",
    "Dissolvant",
    "Crème hydratante",
    "Crème anti-âge",
    "Masque visage",
    "Sérum hydratant",
    "Lotion tonique",
    "Démaquillant",
    "Coton démaquillant",
    "Baume à lèvres",
    "Rouge à lèvres",
    "Mascara",
    "Fond de teint",
    "Correcteur de teint",
    "Poudre compacte",
    "Fard à paupières",
    "Eyeliner",
    "Crayon à sourcils",
    "Crayon à lèvres",
    "Parfum",
    "Eau de Cologne",
    "Crème hydratante corps",
    "Lait pour le corps",
    "Huile pour le corps",
    "Gel anti-cellulite",
    "Crème solaire corps",
    "Après-soleil corps",
    "Autobronzant",
    "Épilateur",
    "Crème dépilatoire",
    "Rasoir électrique",
    "Mousse à raser",
    "Baume après-rasage",
    "Crème anti-rides",
    "Sérum anti-âge",
    "Masque capillaire",
    "Shampoing sec",
    "Spray coiffant",
    "Gel coiffant",
    "Laque",
    "Brosse à dents électrique",
    "Dentifrice blanchissant",
    "Fils dentaires",
] 